const SHORT_FILM_DURATION = 40;

const MAX_WINDOW_SIZE = 1270;
const SMALL_WINDOW_SIZE = 765;

const CARDS_MAX_WINDOW = 12;
const CARDS_MID_WINDOW = 8;
const CARDS_MIN_WINDOW = 5;
const MORE_CARDS_MAX_WINDOW = 3;
const MORE_CARDS_MIN_WINDOW = 2;

export {
  SHORT_FILM_DURATION,
  MAX_WINDOW_SIZE,
  SMALL_WINDOW_SIZE,
  CARDS_MAX_WINDOW,
  CARDS_MID_WINDOW,
  CARDS_MIN_WINDOW,
  MORE_CARDS_MAX_WINDOW,
  MORE_CARDS_MIN_WINDOW
};